<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <link rel="icon" href="../favicon.ico" />
  <link rel="stylesheet" href="../style.css">
  <title>Rails: 更新時に「すでに取得されています」エラーが発生する | Techioz</title>
  <style type="text/css">code{white-space: pre;}</style>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1637770322917058"
     crossorigin="anonymous"></script>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-DRM1ZRNLDN"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-DRM1ZRNLDN');
  </script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "Rails: 更新時に「すでに取得されています」エラーが発生する",
  "author": {
    "@type": "Person",
    "address": "",
    "email": null,
    "identifier": "masyumaroking",
    "name": "masyumaroking"
  },
  "publisher": {
    "@type": "Person",
    "name": "masyumaroking"
  }
}
</script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
  <header>
    <div class="container">
        <h1>Techioz Blog</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Articles</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>
  </header>
  <main>
    <div class="container">
        <article>
                      <h2>Rails:
更新時に「すでに取得されています」エラーが発生する</h2>
                    <h2 id="概要">概要</h2>
                    <p>アプリは属性を検索または初期化します。</p>
                    <pre><code>booking = Booking.where(deal_id: params[&quot;id&quot;]).first_or_initialize
</code></pre>
                    <p>次に、いくつかの追加の属性を更新します</p>
                    <pre><code>    if booking.update!(
        guests: guests,
        names: names,
        time: time)
</code></pre>
                    <p>このコードではエラーが発生します</p>
                    <pre><code>Validation failed: Deal has already been taken
</code></pre>
                    <p>検証コードは</p>
                    <pre><code>  validates_uniqueness_of :deal_id, allow_blank: true, scope: [:experience_id, :time], unless: -&gt; {deal_id.zero? }
</code></pre>
                    <p>最初に first_or_initialize
                    を実行すると、「すでに取得されています」というエラーが発生するのはなぜですか?</p>
                    <p>ありがとう</p>
                    <h2 id="解決策">解決策</h2>
                    <p>これは、experience_id、time の範囲内に同じ
                    deal_id で予約がすでにあることを意味します</p>
                    <p>これは、この一意性検証をモデルに追加したときにデータベースにすでにレコードがあった場合に発生する可能性があります。</p>
                    <p>しかし、これはまったく必要ありません。 deal_id
                    だけを使用した first_or_initialize
                    では、deal_id、experience_id、time
                    の組み合わせは妨げられません</p>
                    <p>さらに、競合状態から保護することはできません</p>
                    <p>更新する前に、デバッグでそのようなレコード数を確認できます。</p>
                    <pre><code>Booking.where(
  deal_id: booking.deal_id,
  experience_id: booking.experience_id,
  time: time,
).count
</code></pre>
        </article>
    </div>
  </main>
  <footer>
    <div class="container">
        <p>&copy; 2024 Techioz. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>