<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <link rel="icon" href="../favicon.ico" />
  <link rel="stylesheet" href="../style.css">
  <title>例外が発生したときに Ruby スクリプトを中止するにはどうすればよいですか? | Techioz</title>
  <style type="text/css">code{white-space: pre;}</style>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1637770322917058"
     crossorigin="anonymous"></script>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-DRM1ZRNLDN"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-DRM1ZRNLDN');
  </script>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Article",
  "headline": "例外が発生したときに Ruby スクリプトを中止するにはどうすればよいですか?",
  "author": {
    "@type": "Person",
    "address": "",
    "email": null,
    "identifier": "masyumaroking",
    "name": "masyumaroking"
  },
  "publisher": {
    "@type": "Person",
    "name": "masyumaroking"
  }
}
</script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
  <header>
    <div class="container">
        <h1>Techioz Blog</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Articles</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </div>
  </header>
  <main>
    <div class="container">
        <article>
                      <h2>例外が発生したときに Ruby
スクリプトを中止するにはどうすればよいですか?</h2>
                    <h2 id="概要">概要</h2>
                    <p>Ruby では、囲まれている begin/rescue
                    ブロックを無視して、プログラムを自動的に中止する例外を発生させることは可能ですか?</p>
                    <h2 id="解決策">解決策</h2>
                    <p>残念ながら、これらの終了回答はどれも機能しません。
                    exit は SystemExit
                    を発生させますが、これはキャッチできます。観察する：</p>
                    <pre><code>begin
  exit
rescue SystemExit
end

puts &quot;Still here!&quot;
</code></pre>
                    <p><span class="citation"
                    data-cites="dominikh">@dominikh</span>
                    が言うように、exit
                    を使用する必要があります。その代わり：</p>
                    <pre><code>begin
  exit!
rescue SystemExit
end

puts &quot;Didn&#39;t make it here :(&quot;
</code></pre>
        </article>
    </div>
  </main>
  <footer>
    <div class="container">
        <p>&copy; 2024 Techioz. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>